<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="keywords" content="Maintain Inventory by item and Werehouse, baan,baanerp,erp,forum,discussion,bulletin board" />
	<meta name="description" content="[Archive] Maintain Inventory by item and Werehouse AFS/DDC/OLE: Function servers" />
	
	<title>Maintain Inventory by item and Werehouse [Archive]  - Baanboard.com</title>
	<link rel="stylesheet" type="text/css" href="../styles.css" />
</head>
<body>
<div class="pagebody">
<div id="navbar"><a href="index.html">Newbaanboard</a> &gt; <a href="index.html">Baan SIGs</a> &gt; <a href="index.html">AFS/DDC/OLE: Function servers</a> &gt; Maintain Inventory by item and Werehouse</div>
<hr />
<div class="pda"></div>

<hr />

<div class="post"><div class="posttop"><div class="username">Ilansu</div><div class="date">8th December 2002, 10:38</div></div><div class="posttext">Hi all <br />
<br />
Im having a problem in getting the error message from a session.<br />
Im trying to run the session  tdilc1120m000 using AFS.<br />
<br />
next.sern=search.for.next.serial.number(temp.cprj,item,temp.cntr,cwar,date)<br />
<br />
stpapi.put.field(&quot;tdilc1120m000&quot;,&quot;tdinv100.cprj&quot;,&quot; &quot;)<br />
stpapi.put.field(&quot;tdilc1120m000&quot;,&quot;tdinv100.item&quot;,item)<br />
stpapi.put.field(&quot;tdilc1120m000&quot;,&quot;tdinv100.cwar&quot;,cwar)<br />
stpapi.put.field(&quot;tdilc1120m000&quot;,&quot;tdinv100.idat&quot;,str$(date))<br />
stpapi.put.field(&quot;tdilc1120m000&quot;,&quot;tdinv100.sern&quot;,str$(next.sern))<br />
stpapi.put.field(&quot;tdilc1120m000&quot;,&quot;tdinv100.kowt&quot;,&quot;1&quot;)<br />
stpapi.put.field(&quot;tdilc1120m000&quot;,&quot;tdinv100.rlcd&quot;,suno)<br />
stpapi.put.field(&quot;tdilc1120m000&quot;,&quot;tdinv100.comp&quot;,str$(get.compnr()))<br />
stpapi.put.field(&quot;tdilc1120m000&quot;,&quot;tdinv100.odat&quot;,str$(date))<br />
stpapi.put.field(&quot;tdilc1120m000&quot;,&quot;tdinv100.pdat&quot;,str$(date))<br />
stpapi.put.field(&quot;tdilc1120m000&quot;,&quot;tdinv100.pqan&quot;,str$(quan))<br />
stpapi.put.field(&quot;tdilc1120m000&quot;,&quot;tdinv100.wtst&quot;,&quot;1&quot;)<br />
<br />
stpapi.insert( &quot;tdilc1120m000&quot;, 1, error.mess )<br />
    if isspace(error.mess) then<br />
        error.mess=stpapi.get.mess.code( &quot;tdilc1120m000&quot; )<br />
 <br />
<br />
I run the session in a debug mode and found that if the item doesnt have a cost price for the requested date the there is a set.input.error() function .<br />
When I run my ASF with the same date I dont get that message and the rest of my code is not executed as it should.(of course there was no insert)<br />
The session get stuck after trying to put value in the subsession tdilc1121s000.<br />
if isspace(error.mess) then<br />
     stpapi.handle.subproc(&quot;tdilc1120m000&quot;,&quot;tdilc1121s000&quot;,&quot;add&quot;)<br />
     stpapi.continue.process(&quot;tdilc1120m000&quot;, error.mess)            <br />
     if isspace(error.mess) then<br />
       stpapi.put.field(&quot;tdilc1121s000&quot;,&quot;tdilc102.serb&quot;,&quot;1&quot;)<br />
       tpapi.put.field(&quot;tdilc1121s000&quot;,&quot;tdilc102.stun&quot;,tiitm001.cuni)<br />
       stpapi.put.field(&quot;tdilc1121s000&quot;,&quot;tdilc102.qstr&quot;,str$(quan))<br />
       stpapi.put.field(&quot;tdilc1121s000&quot;,&quot;tdilc102.qstk&quot;,str$(quan))<br />
       stpapi.insert( &quot;tdilc1121s000&quot;, 1, error.mess )<br />
         endif<br />
     stpapi.handle.subproc(&quot;tdilc1120m000&quot;,&quot;tdilc1121s000&quot;,&quot;kill&quot;)<br />
     stpapi.end.session(&quot;tdilc1121s000&quot;)<br />
     if isspace(error.mess) then<br />
        stpapi.put.field(&quot;tdilc1120m000&quot;,&quot;tdinv100.wtst&quot;,&quot;2&quot;)<br />
        stpapi.update( &quot;tdilc1120m000&quot;, 1, error.mess )<br />
     endif<br />
endif<br />
stpapi.end.session(&quot;tdilc1120m000&quot;)<br />
<br />
<br />
Any suggestions ?<br />
<br />
Thanks <br />
Ilan S</div></div><hr />


<div class="post"><div class="posttop"><div class="username">Ilansu</div><div class="date">9th December 2002, 11:34</div></div><div class="posttext">In debug mode I noticed that after <br />
stpapi.insert( &quot;tdilc1120m000&quot;, 1, error.mess )<br />
erro.mess=&quot;&quot;<br />
but after   <br />
error.mess=stpapi.get.mess.code( &quot;tdilc1120m000&quot; )<br />
error.mess=&quot;                           &quot; (error.mess contains about 10 spaces)<br />
<br />
Should I check len(error.mess ) ?<br />
<br />
Ilan S</div></div><hr />


<div class="post"><div class="posttop"><div class="username">mark_h</div><div class="date">9th December 2002, 13:43</div></div><div class="posttext">There are two things you could try.<br />
<br />
After the insert - check the transaction status to make sure you have one that is open.  I recommend this anyway - that way once you and process in the sub-sessions and then return to the main session, you can check to see if you have a closed transaction status.  I use that to make sure that my transaction was processed. If not I delete the record and tell the user that there was a problem with the input record.  <br />
<br />
Before running this function server I validate the data.  So I make sure they gave me a valid item, lot, date, etc.  I am not sure if it is possible for you to check this before running the code.  Is there something you can do before processing? Sometimes when I can not trap errors from a function server I trap them before calling the session.  It is not always easy, but it beats having a hung session in the background.<br />
<br />
Mark</div></div><hr />



</div>
</body>
</html>