<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="keywords" content="db.retry.point, baan,baanerp,erp,forum,discussion,bulletin board" />
	<meta name="description" content="[Archive] db.retry.point Tools Development" />
	
	<title>db.retry.point [Archive]  - Baanboard.com</title>
	<link rel="stylesheet" type="text/css" href="../styles.css" />
</head>
<body>
<div class="pagebody">
<div id="navbar"><a href="../index.html">Newbaanboard</a> &gt; <a href="../index.html">Baan Quick Support: Functional &amp; Technical</a> &gt; <a href="../index.html">Tools Development</a> &gt; db.retry.point</div>
<hr />
<div class="pda"></div>

<hr />

<div class="post"><div class="posttop"><div class="username">rahul.kolhe22</div><div class="date">30th January 2009, 12:01</div></div><div class="posttext">Hi,<br />
       I am trying to trace one of the old code in which I came across the condition as shown below<br />
<br />
<br />
...<br />
db.retry.point()<br />
<br />
select        table1fields.*<br />
from          table1<br />
where        condition<br />
selectdo<br />
        ...<br />
        ...<br />
        commit.transaction()<br />
selecteos<br />
        ...<br />
        ...<br />
        commit.transaction()<br />
endselect<br />
<br />
db.retry.point()<br />
select        table2fields.*<br />
from          table2<br />
where        condition<br />
selectdo<br />
        ...<br />
        ...<br />
endselect<br />
<br />
if no.error then<br />
        commit.transaction()<br />
else<br />
        abort.transaction()<br />
endif<br />
<br />
<br />
Here when the first db.retry.point is been set, the control never goes in the first selectdo clause neither in selecteos. So nethier the commit nor the abort transaction is been executed.<br />
<br />
After that other db.retry.point is been set. As far as I know we cannot set 2 db.retry.point without commiting or aborting the previous retry point.<br />
<br />
Also the code I am tracing is very old and is in use and frequently executed, so there are no chances that it may be a bug.<br />
<br />
Can anyone please let me know whether there is any variable or some debugger command or something similar using which I can know on execution of which statement the first db.retry.point is been unset/removed.<br />
<br />
Any suggestions are welcomed.<br />
<br />
Thanks in advance.<br />
<br />
--Rahul</div></div><hr />


<div class="post"><div class="posttop"><div class="username">_Ralph_</div><div class="date">30th January 2009, 15:10</div></div><div class="posttext">You can use <br />
<br />
db.retry.hit()<br />
<br />
Return values<br />
<br />
0 Retry point defined but not returned to. <br />
&gt;0 System returned to retry point. <br />
-1 No Retry point defined <br />
-2 Stack Error (Programming error in script. A db.retry.point() was done at a deeper stack level) <br />
<br />
<br />
and in my opinion.. that is a bug xD</div></div><hr />


<div class="post"><div class="posttop"><div class="username">rahul.kolhe22</div><div class="date">2nd February 2009, 06:46</div></div><div class="posttext">Hi,<br />
       Thanks a lot Ralph for your immediate reply.<br />
<br />
       I think I have confused you.<br />
<br />
The very first thing is that I am not supposed to make the changes in the script.<br />
Secoundly, setting of two db.retry.point will give the fatual error. I can see the code executing in the debug mode but there is no fatual error. It means I am missing some thing somewhere.<br />
<br />
So my problem is can anyone just help me out to know at which point (or execution of statement) the first retry point set is been unset/nutralized.<br />
<br />
I want to know that while debugging is there any command which can help me to know that the retry point which is been set is been removed.<br />
<br />
Thanks in advance<br />
<br />
--Rahul</div></div><hr />


<div class="post"><div class="posttop"><div class="username">_Ralph_</div><div class="date">2nd February 2009, 14:29</div></div><div class="posttext">two db.retry.point() will show errors only if a db transaction(update, delete, insert) exists between. If there is nothing in between, no error should occur. As you are on LN mayber there is some transaction happening on DALs that you are not tracing.<br />
<br />
I do not know anyway to know when the db.retry.point was hinted using the debugger.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">toolswizard</div><div class="date">2nd February 2009, 17:11</div></div><div class="posttext">Unless there has been an actual transaction i.e. update, delete, I don't think you will get an error.  If you do, it is usually a &quot;transaction on&quot; error.<br />
<br />
The best way to test db.retry points is to use the bshell envrionment setting -set TEST_RETRY=1.  This wil allow you to test the code to make sure it is running the second time the same as the first.  So when ever you hit a transaction, or commit transaction, it will always fail once, and then recover.<br />
<br />
If you want to force a fatal error, set the retry count greater than the max retry limit.  11 usually works.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">rahul.kolhe22</div><div class="date">3rd February 2009, 11:28</div></div><div class="posttext">Hi,<br />
     Thanks a lot Ralph and William.<br />
<br />
     William your idea to trace db.retry.point was superb. It helped me. Also Ralph your information was really usefull.<br />
<br />
    Thanks again<br />
<br />
Regards,<br />
--Rahul</div></div><hr />



</div>
</body>
</html>