<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="keywords" content="Dal update error return value -12, baan,baanerp,erp,forum,discussion,bulletin board" />
	<meta name="description" content="[Archive] Dal update error return value -12 Tools Development" />
	
	<title>Dal update error return value -12 [Archive]  - Baanboard.com</title>
	<link rel="stylesheet" type="text/css" href="../styles.css" />
</head>
<body>
<div class="pagebody">
<div id="navbar"><a href="../index.html">Newbaanboard</a> &gt; <a href="../index.html">Baan Quick Support: Functional &amp; Technical</a> &gt; <a href="../index.html">Tools Development</a> &gt; Dal update error return value -12</div>
<hr />
<div class="pda"></div>

<hr />

<div class="post"><div class="posttop"><div class="username">Noor Jahan</div><div class="date">15th September 2015, 06:55</div></div><div class="posttext">Hi all,<br />
<br />
I have problem during dal. update<br />
<br />
when iam setting the dal.set.property for particular  field.<br />
<br />
Iam  getting the retrun value -12 in the dal.update() function.<br />
<br />
The field is string filed ibd008.dori and its value getting updated is  &quot;1&quot;<br />
is it because the number value even though iam setting the field value as &quot;test&quot;<br />
as runtime same error iam getting during update.<br />
<br />
Please help<br />
<br />
Regards</div></div><hr />


<div class="post"><div class="posttop"><div class="username">bhushanchanda</div><div class="date">15th September 2015, 09:03</div></div><div class="posttext">Hi,<br />
<br />
Yes. If its a number field i.e. say double with domain tcamnt and you are updating as a string field, it will return -12.<br />
<br />
Also, not sure about your version, but dal.set.property() is depreciated. Use dal.set.field() instead.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">vahdani</div><div class="date">15th September 2015, 10:07</div></div><div class="posttext">-12 or DALHOOKERROR is the standard value returned if there is an error detected during DAL processing. In such cases you can always check the error message usibf for example show.dal.messages() to find out what was wrong:<br />
<br />
<br />
	long	l.ret<br />
	<br />
	db.retry.point()<br />
	dal.new.object(&quot;tcibd008&quot;)<br />
	....<br />
	dal.set.field(&quot;tcibd008.dori&quot;, value1)<br />
	dal.set.field(&quot;tcibd008.xxxx&quot;, value2)<br />
	....<br />
	l.ret = dal.save.object(&quot;tcibd008&quot;)<br />
	if l.ret = 0 then<br />
		commit.transaction()<br />
	else<br />
		abort.transaction()<br />
		show.dal.messages()<br />
	endif</div></div><hr />


<div class="post"><div class="posttop"><div class="username">Noor Jahan</div><div class="date">15th September 2015, 10:54</div></div><div class="posttext">Hi Thanks all,<br />
<br />
<br />
<br />
Even though iam converting the filed value to string with str$ function<br />
before updating iam, getting the same error</div></div><hr />


<div class="post"><div class="posttop"><div class="username">bhushanchanda</div><div class="date">15th September 2015, 11:22</div></div><div class="posttext">Hi,<br />
<br />
As Vahdani rightly said, use dal.get.error.message() to get the error message. Check if you are passing any special character. Try different variations like use a variable, assign it value and then use it in dal function.<br />
<br />
e.g. <br />
<br />
a = str$(1)<br />
dal...<br />
<br />
Also, it will help if you post your code.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">Noor Jahan</div><div class="date">15th September 2015, 13:53</div></div><div class="posttext">Hi,<br />
<br />
My code <br />
<br />
ex:<br />
dal.set.property(.....awibd008.dori,hold.dori...)<br />
<br />
ibdoo8.dori is orientation field in table ibd008<br />
<br />
iam getting the error from dal.get.error.message is <br />
<br />
&quot;orienation not found in foundation table&quot;---eror<br />
<br />
<br />
What it means..</div></div><hr />


<div class="post"><div class="posttop"><div class="username">bhushanchanda</div><div class="date">15th September 2015, 14:03</div></div><div class="posttext">Hi,<br />
<br />
It means that there is an existing DAL present for the table you are trying to update and it has a field/property hook which has a check. Also check the table definition. It might be referring to some other table for the field you are trying to update.<br />
<br />
As it looks like a customized table, its difficult to tell the exact table name.<br />
<br />
Basic idea is, <br />
<br />
There is an Orientation Master Table (X) which doesn't have any value named Y which you are trying to update in your table.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">Noor Jahan</div><div class="date">16th September 2015, 06:54</div></div><div class="posttext">Tnaks bhusan,<br />
<br />
<br />
But stil iam fcing the problem ihave chekced the DAl for the table ibd008<br />
<br />
it has written<br />
function extern long awibd008.dori.check(long has_changed)<br />
{<br />
	if not isspace(awibd008.dori) then<br />
		if not check.value(awibd008.dori,awibd.found.dori) then<br />
			RET.ERR(&quot;Orientation not found in Foundation Table&quot;)<br />
		endif<br />
		<br />
	endif<br />
	return(0)<br />
}<br />
<br />
<br />
due to whcih iam getting the error.<br />
<br />
<br />
but iam not geting wat it means<br />
<br />
<br />
in program i have writen.<br />
<br />
<br />
dal.set.property(&quot;awibd008&quot;, tawibd008, &quot;awibd008.dori&quot;, hold.ibd008.dori, DAL_UPDATE)<br />
<br />
<br />
PLease help</div></div><hr />


<div class="post"><div class="posttop"><div class="username">bhushanchanda</div><div class="date">16th September 2015, 08:53</div></div><div class="posttext">Hi,<br />
<br />
I can see there is a function call checking for a return value and its returning as false.<br />
<br />
Check function check.value() in your DAL script. Put the DAL under debugger and figure out the issue.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">Ajesh</div><div class="date">17th September 2015, 07:18</div></div><div class="posttext">Hi,<br />
<br />
My code <br />
<br />
ex:<br />
dal.set.property(.....awibd008.dori,hold.dori...)<br />
<br />
ibdoo8.dori is orientation field in table ibd008<br />
<br />
iam getting the error from dal.get.error.message is <br />
<br />
&quot;orienation not found in foundation table&quot;---eror<br />
<br />
<br />
What it means..<br />
<br />
Does this Orientation field has any references to other Table. To me it seems Orientation field refers to a certain Table named as Foundation Table. <br />
<br />
Try inserting the same value in Foundation Table before you set the dal.field for the orientation field.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">Noor Jahan</div><div class="date">17th September 2015, 14:15</div></div><div class="posttext">Hi ,<br />
<br />
I haev found that in check .value function its checking the record in table ibd025<br />
where the record is present but still its returning false in select empty,<br />
<br />
Whereas i have put the DAL in debugging mode<br />
but while ruunig the sesion the control is not going to the DAL function<br />
when the dal.set.property hit or even the dal.upadte function hit<br />
so iam nto able to find the problem.<br />
<br />
How to debug it when the control goes to the DAL fucntion.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">bhushanchanda</div><div class="date">17th September 2015, 14:29</div></div><div class="posttext">Hi,<br />
<br />
dal.set.property() should execute the DAL if its in debug mode.<br />
<br />
1. Check if you are in the same VRC where the debugged object is.<br />
2. Close any GTM display (ttaad4100/ttaad4500) if opened<br />
<br />
If the above 2 doesn't solve the issue, log out and log back in.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">Noor Jahan</div><div class="date">18th September 2015, 06:33</div></div><div class="posttext">hi Bhusan,<br />
<br />
many thanks,it resolved.<br />
<br />
Regards</div></div><hr />


<div class="post"><div class="posttop"><div class="username">Prudhvi0009</div><div class="date">30th November 2018, 11:11</div></div><div class="posttext">i'm unable to update and commit the fields in table tccom0009<br />
while checked in debugger i found that the ret value is throwing -12 value <br />
for the below dal.update.<br />
<br />
could you suggest what may be the issue and in which cases does it occur?<br />
<br />
This situation is occurring for few records only.<br />
for few of them it's updating and committing the transaction.<br />
 <br />
dal.update(&quot;tccom009&quot;,ttccom009,ret,FALSE,DB.RETRY)<br />
commit.transaction()</div></div><hr />



</div>
</body>
</html>