<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="keywords" content="Wrong Use of DAL Engine, baan,baanerp,erp,forum,discussion,bulletin board" />
	<meta name="description" content="[Archive] Wrong Use of DAL Engine Tools Development" />
	
	<title>Wrong Use of DAL Engine [Archive]  - Baanboard.com</title>
	<link rel="stylesheet" type="text/css" href="../styles.css" />
</head>
<body>
<div class="pagebody">
<div id="navbar"><a href="../index.html">Newbaanboard</a> &gt; <a href="../index.html">Baan Quick Support: Functional &amp; Technical</a> &gt; <a href="../index.html">Tools Development</a> &gt; Wrong Use of DAL Engine</div>
<hr />
<div class="pda"></div>

<hr />

<div class="post"><div class="posttop"><div class="username">Amit_Jain</div><div class="date">13th July 2016, 09:26</div></div><div class="posttext">Hi<br />
<br />
My process session halts at dal.save.object (for new records) and I get an Application error &quot;Wrong use of  DAL Engine&quot;. <br />
<br />
Is there any way by which we can suppress this error message, because this message stops the flow of baan program. A user has to exit or Ignore this error message to continue with then program.<br />
<br />
refer my code snippet here:<br />
<br />
select 	tiedm100.* <br />
	from 	tiedm100 <br />
	where 	tiedm100._index1 = {:eitm, :revi}<br />
	as set with 1 rows<br />
	selectdo		<br />
		return<br />
	selectempty  <br />
		dal.new.object(&quot;tiedm100&quot;)<br />
		dal.set.field(&quot;tiedm100.eitm&quot;, eitm)<br />
		dal.set.field(&quot;tiedm100.revi&quot; ,  revi)<br />
		dal.set.field(&quot;tiedm100.dsca&quot; ,  dsca)<br />
		if trim$(engi) &lt;&gt; &quot;0&quot; then<br />
			dal.set.field(&quot;tiedm100.engi&quot; ,  engi)<br />
		endif<br />
		if not isspace(indt) then<br />
			dal.set.field(&quot;tiedm100.indt&quot; ,  utc.indt)<br />
		endif<br />
		|if not isspace(exdt) then<br />
		|	dal.set.field(&quot;tiedm100.exdt&quot; ,  utc.exdt)<br />
		|endif<br />
		dal.set.field(&quot;tiedm100.unom&quot; ,  val(unom))<br />
		dal.set.field(&quot;tiedm100.uset&quot; ,  uset)<br />
		dal.set.field(&quot;tiedm100.csig&quot; ,  csig)<br />
		dal.set.field(&quot;tiedm100.cuni&quot; ,  cuni)<br />
		dal.set.field(&quot;tiedm100.dscb&quot; ,  dscb)<br />
		dal.set.field(&quot;tiedm100.dscc&quot; ,  dscc)<br />
		dal.set.field(&quot;tiedm100.dscd&quot; ,  dscd)<br />
		dal.set.field(&quot;tiedm100.rele&quot; ,  tiedm.rele.indesign)<br />
		dal.set.field(&quot;tiedm100.cwun&quot; ,  &quot;lbs&quot;)<br />
		dal.set.field(&quot;tiedm100.wght&quot; ,  val(wght))<br />
		ret = dal.save.object(&quot;tiedm100&quot;, err.mess,db.return.error)<br />
		if ret = 0 then<br />
			error = 0<br />
			commit.transaction()<br />
		else<br />
			dal.get.error.message(err.mess)<br />
			status = seq.puts( err.mess &amp; &quot;|&quot; &amp; ts,fp2)	<br />
			abort.transaction()<br />
			counterbad = counterbad + 1<br />
			error = 1<br />
		endif<br />
	endselect</div></div><hr />


<div class="post"><div class="posttop"><div class="username">bhushanchanda</div><div class="date">13th July 2016, 11:11</div></div><div class="posttext">Hi,<br />
<br />
What is the error message return by dal.get.error.message() and what is the return value of dal.save.object().<br />
<br />
There is a possibility that record already exists or may be its due to bad data due to domain mismatch.<br />
<br />
Instead of suppressing, you may try to solve the issue. For suppressing, you can try setting error.bypass = true</div></div><hr />


<div class="post"><div class="posttop"><div class="username">vahdani</div><div class="date">14th July 2016, 13:47</div></div><div class="posttext">Hi Amit,<br />
<br />
I Think your dal.save.object() call is wrong. Especially the variable err.mess is not allowed in DAL2. Please use only <br />
<br />
               ret = dal.save.object(&quot;tiedm100&quot;)</div></div><hr />


<div class="post"><div class="posttop"><div class="username">Amit_Jain</div><div class="date">15th July 2016, 10:20</div></div><div class="posttext">Hi Vahdani<br />
<br />
This code piece was a result of some Trial and error, which I did to suppress the error message popup. My original code has ret = dal.save.object(&quot;tiedm100&quot;).<br />
<br />
@Bhushan: I am capturing return value and I know some of the data to be uploaded is not correct. <br />
The problem is the size of data is big and I don't want my program to halt execution during upload.<br />
<br />
I will try error.bypass=true and get back to you.<br />
<br />
Thanks Vahdani and Bhushan for your valuable comments.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">vamsi_gujjula</div><div class="date">15th July 2016, 12:09</div></div><div class="posttext">ret = dal.save.object(&quot;tiedm100&quot;, err.mess,db.return.error)<br />
<br />
From the guide function long dal.save.object  (string tbl.name [, long error.flag])<br />
<br />
should have been dal.save.object(&quot;tiedm100&quot;,db.return.error)</div></div><hr />



</div>
</body>
</html>